name: ci

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ruby/setup-ruby@v1.197.0
        with:
          bundler-cache: true

      - name: Setup Hotsheet
        run: bin/setup

      - name: Run linters
        run: bin/fastcheck

      - name: Run tests
        run: bin/check
